spring:
  application:
    name: blogapp

  datasource:
    url: jdbc:postgresql://localhost:5432/BlogPostApp
    username: postgres
    password: Tg&f0Jwnf
    driver: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/master.yaml